# Generated by Django 2.0.3 on 2018-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default='This is a description'),
            preserve_default=False,
        ),
    ]
